swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Shipyard"
host: "localhost:4242"
basePath: "/v1"
schemes:
- "http"
paths:
  /ships:
    post:
      summary: "Add ship to shipyard"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Ship object to be added to shipyard"
        required: true
        schema:
          $ref: "#/definitions/Ship"
      responses:
        201:
          description: "Success"
          schema:
            $ref: "#/definitions/ShipWithId"
    get:
      summary: "Fetches list of Ships"
      description: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ShipArray"
definitions:
  Ship:
    type: "object"
    required:
    - "name"
    - "speed"
    properties:
      name:
        type: "string"
        example: "Enterprise D"
      speed:
        type: "string"
        example: "Warp 9"
  ShipWithId:
    allOf:
      - $ref: "#/definitions/Ship"
      - properties:
          id:
            type: 'number'
            example: 1
  ShipArray:
    type: 'array'
    items:
      $ref: "#/definitions/ShipWithId"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"