### Create new ship
POST http://localhost:4242/v1/ships
Content-Type: application/json

{
  "name": "Concordia",
  "speed": "3.5"
}

> {%
    client.test("Create new ship", function() {
        client.assert(response.status === 201, "Status code should be 201 in ships-post.http scratch.");
        client.assert(response.body.name === "Concordia", "Ship name should be 'Concordia' in ships-post.http scratch.");
        client.assert(response.body.speed === "3.5", "Speed should be '3.5' in ships-post.http scratch.");
        client.assert(typeof response.body.id === 'number', "Id should be number in ships-post.http scratch.");
        client.assert(response.contentType.mimeType === "application/json", "Content-Type should be 'application/json' in ships-get.http scratch.");
    });
%}

###

### Create new ship
POST http://localhost:4242/v1/ships
Content-Type: application/json

{
  "name": "Concordia"
}

> {%
    client.test("Create new ship without speed fails", function() {
        client.assert(response.status === 422, "Status code should be 422 in ships-post.http scratch.");
    });
%}

###
